theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
mouse = false
auto-completion = true
auto-format = true
bufferline = "always"
idle-timeout = 20
completion-trigger-len = 1
cursorline = true
rulers = []
color-modes = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true
character = "┊"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-type", "total-line-numbers", "file-encoding"]
center = []
right = ["selections", "primary-selection-length", "position", "position-percentage", "spacer", "diagnostics", "workspace-diagnostics", "version-control"]

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = " "
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "→"

[keys.normal."space"]
w= ":w"
q = ":q"
c = ":buffer-close"
"/" = ["search_selection", "global_search"]
o = "file_picker_in_current_buffer_directory"
g = ":sh ~/dotfiles/scripts/helix.sh git $(~/dotfiles/scripts/helix.sh getfileinfo)"
e = ":sh ~/dotfiles/scripts/helix.sh explorer $(~/dotfiles/scripts/helix.sh getfileinfo)"
B = ":sh ~/dotfiles/scripts/helix.sh blame $(~/dotfiles/scripts/helix.sh getfileinfo)"
r = ":pipe ~/dotfiles/scripts/helix.sh getfileinfo"
x = ":sh ~/dotfiles/scripts/helix.sh copy $(~/dotfiles/scripts/helix.sh getfileinfo | awk \"{ print \\$1 }\")"

[keys.normal."]"]
b = "goto_next_buffer"
e = ["extend_to_line_bounds", "delete_selection", "paste_after"]

[keys.normal."["]
b = "goto_previous_buffer"
e = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
