theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
mouse = false
auto-completion = true
auto-format = true
bufferline = "always"
idle-timeout = 20

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true
character = "▏"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-type", "total-line-numbers", "file-encoding"]
center = []
right = ["selections", "primary-selection-length", "position", "position-percentage", "spacer", "diagnostics", "workspace-diagnostics", "version-control"]

[keys.normal]
space.w= ":w"
space.q = ":q"

[keys.normal."]"]
b = "goto_next_buffer"

[keys.normal."["]
b = "goto_previous_buffer"
