#!/bin/bash

## Get data
STATUS="$(playerctl status)"
COVER="/tmp/.music_cover.png"
MUSIC_DIR="$HOME/Music"

## Get status
get_status() {
	if [[ $STATUS == "Playing" ]]; then
		echo "images/icons/music/pause-button.png"
	else
		echo "images/icons/music/play-button.png"
	fi
}

## Get song
get_song() {
	song=`playerctl metadata title`
	if [[ -z "$song" ]]; then
		echo "Offline"
	else
		echo "$song"
	fi	
}

## Get artist
get_artist() {
	artist=`playerctl metadata artist`
	if [[ -z "$artist" ]]; then
		echo ""
	else
		echo "$artist"
	fi	
}

## Get time
get_time() {
	time=`mpc status | grep "%)" | awk '{print $4}' | tr -d '(%)'`
	if [[ -z "$time" ]]; then
		echo "0"
	else
		echo "$time"
	fi	
}
get_ctime() {
	position=$(playerctl position | sed 's/\.//')
	if [[ -z "$position" ]]; then
		echo "0:00"
	else
		echo "$position"
	fi	
}
get_ttime() {
	position=$(playerctl position | sed 's/\.//')
    total_time=$(playerctl metadata mpris:length)
    percent=$((($position * 100) / $total_time))
	if [[ -z "$percent" ]]; then
		echo "0"
	else
		echo "$percent"
	fi	
}

## Get cover
get_cover() {
	COVER=$(playerctl metadata mpris:artUrl)
    status=$(playerctl -s status)
    if [ -z "${status}" ] || [ "$status" = "Stopped" ];then
		echo "images/music.png"
	else
		echo "$COVER"
	fi
}

## Execute accordingly
if [[ "$1" == "--song" ]]; then
	get_song
elif [[ "$1" == "--artist" ]]; then
	get_artist
elif [[ "$1" == "--status" ]]; then
	get_status
elif [[ "$1" == "--time" ]]; then
	get_time
elif [[ "$1" == "--ctime" ]]; then
	get_ctime
elif [[ "$1" == "--ttime" ]]; then
	get_ttime
elif [[ "$1" == "--cover" ]]; then
	get_cover
elif [[ "$1" == "--toggle" ]]; then
	playerctl play-pause
elif [[ "$1" == "--next" ]]; then
	{ playerctl next; get_cover; }
elif [[ "$1" == "--prev" ]]; then
	{ playerctl previous; get_cover; }
fi
