#!/bin/bash

if [[ "$1" == "--tr" ]]; then
	wezterm &

elif [[ "$1" == "--ff" ]]; then
	firefox &

elif [[ "$1" == "--ch" ]]; then
	$BROWSER &

elif [[ "$1" == "--fm" ]]; then
	thunar ~ &

elif [[ "$1" == "--ge" ]]; then
	wezterm start -- nvim ~/stuff.txt &

elif [[ "$1" == "--dc" ]]; then
	discord &

elif [[ "$1" == "--tg" ]]; then
	telegram-desktop &

elif [[ "$1" == "--rd" ]]; then
	$BROWSER --new-tab "https://reddit.com"

elif [[ "$1" == "--ml" ]]; then
	$BROWSER --new-tab "https://mail.google.com"

elif [[ "$1" == "--scl" ]]; then
	$BROWSER --new-tab "https://soundcloud.com/"

elif [[ "$1" == "--pow" ]]; then
	xfce4-power-manager-settings &

elif [[ "$1" == "--nm" ]]; then
	networkmanager_dmenu

elif [[ "$1" == "--ws" ]]; then
	hyprctl dispatch workspace $2

fi
